name: Manual Release Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run killer-release task
        run: ./gradlew :killer:assembleRelease

      - name: Print build folder tree
        run: |
          echo "Attempting to print tree structure of build directories..."
          if command -v tree &> /dev/null
          then
            find . -type d -name build -exec echo "Listing for {}" \; -exec tree {} \;
          else
            echo "tree command not found, using ls -R instead for build directories"
            find . -type d -name build -exec echo "Listing for {}" \; -exec ls -R {} \;
          fi
